name: Test-HA
on:
  workflow_call:
jobs:
  qualif:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Kind/K8S Cluster
      uses: ./.github/actions/setup
      with:
        install-chaos: true
    - name: Create namespace
      shell: bash
      run: |
        kubectl create namespace ds
    - name: Setup TLS Certificates
      shell: bash
      run: |
        openssl req -x509 -newkey rsa:4096 -nodes -subj '/CN=example.org' -keyout tls.key -out tls.crt -days 365
        cp tls.crt ca.crt
        kubectl --namespace ds create secret generic myval-certs --from-file=./tls.crt --from-file=./tls.key --from-file=./ca.crt
    - name: Deploy OpenLDAP cluster
      shell: bash
      run: |
        helm install --namespace ds openldap -f .bin/myval.yaml .
        kubectl --namespace ds get events --watch &
        kubectl --namespace ds rollout status sts openldap; ec=$?
        kubectl --namespace ds logs -l app.kubernetes.io/name=openldap --all-containers=true --timestamps=true --prefix=true --since=6h --tail=-1 --ignore-errors
        exit $ec
    - name: Test OpenLDAP database via TLS
      uses: ./.github/actions/tls-access
      with:
        port: 30636
    # - name: MemberOf test to OpenLDAP database
    #   shell: bash
    #   run: |
    #       ( LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' "(memberOf=cn=testgroup,ou=Group,dc=example,dc=org)" | tee /tmp/test-write.txt | awk -f .bin/ldif2json | jq ) || /bin/true
    #       responses=$(grep "numResponses" /tmp/test-write.txt | cut -d ":" -f 2 | tr -d ' ')
    #       [ $responses -lt 2 ] || exit 1
    #       grep -q "uid=test1,ou=People,dc=example,dc=org" /tmp/test-write.txt || exit 1
    - name: Validate self service pwd access
      shell: bash
      run: |
          curl ssl-ldap2.example:8080
    - name: Verify TLS Certificate Materials
      shell: bash
      run: |
          echo | openssl s_client -showcerts -servername example.org -connect localhost:30636 2>/dev/null | openssl x509 -inform pem -noout -text > /tmp/test-cert.txt
          if ! grep -q "CN = example.org" /tmp/test-cert.txt; then  echo exit 1; fi
    - name: Run tests against the OpenLDAP cluster
      run: .bin/tests.sh -d 100
    - name: Enable chaos within cluster to test cluster resiliance
      shell: bash
      run: |
          kubectl apply -f .bin/chaos.yaml
#    - name: Run tests again, now amid chaos
#      run: .bin/tests.sh -d 100
    - name: Extended testing over a period of 20 minutes amid chaos
      shell: bash
      run: |
          for i in {1..20}; do echo $i of 20; LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' > /dev/null && sleep 60 ; done
